---
title: "APM466 A1"
author: "Jin Wen Lin"
date: "February 2023"
output:
  html_document: default
---

```{r}
# Load the bonds data
## library the readr packages to read the data
library(readr)
data <- read_csv("~/APM466 A1/selected_data.csv")
```


```{r}
# maturity date
maturity_date <- data$`Maturity Date`
# coupon rate
coupon <- data$Coupon
# dates of collecting the data
dates <-c("2023-01-16", "2023-01-17", "2023-01-18", "2023-01-19", "2023-01-20", "2023-01-23", "2023-01-24", "2023-01-25", "2023-01-26", "2023-01-27")
# Display the prices of each bond for each date through matrix representation
bond_prices <- matrix(c(data$`1/16/2023`, data$`1/17/2023`, data$`1/18/2023`, data$`1/19/2023`, data$`1/20/2023`, data$`1/23/2023`, data$`1/24/2023`, data$`1/25/2023`, data$`1/26/2023`, data$`1/27/2023`), nrow = 10, ncol = 10, byrow = TRUE)
dates
```

## Yield to Maturity

```{r}
# use the package jrvFinance to do the computations later on
# install.packages("jrvFinance")
# library the package jrvFinance
library(jrvFinance)

# Computation of yield to maturity for each bond
## initialize a ytm matrix so it stores the ytm for each bond
ytm <- matrix('numeric', nrow = 10, ncol = 10)
## start to compute ytm using for loop
for(j in c(1:10)) {
  # price for a specific bond
  price = bond_prices[, j]
  for (i in c(1:10)) {
    # apply the function bond.yield to calculate ytm for each bond
    ytm[i, j] <-
      bond.yield(
        dates[i],
        maturity_date[j],
        coupon[j],
        freq = 2,
        price[i],
        #default
        convention = c("30/360", "ACT/ACT", "ACT/360", "30/360E"),
        comp.freq = 2,
        #default
        redemption_value = 100
      )
  }
}
```

```{r}
# plot of the ytm for each bond (might over 5 years)
## the 10 workdays
day <- c(1,2,3,4,5,6,7,8,9,10)
# Add extra space for the plot so legend can be added
par(mar=c(5, 8, 8, 8), xpd=TRUE)
plot(day, ytm[1, ], type = "o", main = "YTM Curves for the Selected Bonds", 
     xlab = "10 workdays start from 2023-01-16", ylab = "YTM", ylim = c(0.025, 0.03), col = "black")
lines(day, ytm[2, ], type = "o", col = "red")
lines(day, ytm[3, ], type = "o", col = "darkorange")
lines(day, ytm[4, ], type = "o", col = "yellow")
lines(day, ytm[5, ], type = "o", col = "aquamarine")
lines(day, ytm[6, ], type = "o", col = "blue")
lines(day, ytm[7, ], type = "o", col = "purple")
lines(day, ytm[8, ], type = "o", col = "darkgreen")
lines(day, ytm[9, ], type = "o", col = "pink")
lines(day, ytm[10, ], type = "o", col = "brown")

colors = c("black", "red", "darkorange", "yellow", "aquamarine4", "blue", "purple", "darkgreen", "pink", "brown")
#Legend
legend("topright", pch = c(15,15), inset = c(-0.4, 0), legend = data$`Bond name`, col = colors, cex = 0.5)
```
  
## Spot Rate
```{r}
# Calculation of dirty price
## Initialize dirty first so it will store the dirty prices for each bond.
dirty <- matrix('numeric', nrow = 10, ncol = 10)
## Computation of dirty prices on each date for each bond
for(j in 1:10) {
  for (i in 1:10) {
    # apply the function bond.TCF to calculate dirty prices for each bond
    dirty[j, i] <-
      bond.TCF(dates[j], maturity_date[i], coupon[i])$accrued + bond_prices[j, i]
  }
}

# Figure out the cash flow (P_i) for calculating the spot rates
cash_flow <- list()
for (i in 1:10){
  cash_flow = bond.TCF(dates[i], maturity_date[i], coupon[i], freq = 2)$cf
  print(cash_flow)
}
```

```{r}
#cash flows for each maturity date (from above results)
c1 <- c(rep(1.75, 10), 101.75)
c2 <- c(rep(1, 10), 101)
c3 <- c(rep(1.125, 12), 101.125)
c4 <- c(rep(2.875, 12), 102.875)
c5 <- c(rep(1.125, 13), 101.125)
c6<- c(rep(0.25, 15), 100.25)
c7 <- c(rep(0.75, 16), 100.75)
c8 <- c(rep(0.75, 17), 100.75)
c9 <- c(rep(1, 18), 101)
c10 <- c(rep(1.25, 19), 101.25)
```


```{r}
# time to maturity for each bond in years 
time <- matrix('numeric', nrow = 10, ncol = 10)
for (i in c(1:10)){
  for (j in c(1:10)){
    time[i,j] = yearFraction(dates[i], maturity_date[j], freq = 2)
  }
}
```

```{r}
# spot curve (derive from the equation for dirty price)
## store the spot rates for each bond as a matrix
spot <- matrix('numeric', nrow = 10, ncol = 10)
## Calculations of spot rates
for (i in 1:10){
  # set each functions equal to zero and calculate the root, the spot rate for each bond
  
  function1 <- function(x) as.numeric(dirty[i, 1])-c1[1]*(1+x/2)^(-2*(0.5))- 
    c1[2]*(1+x/2)^(-2*(1))-c1[3]*(1+x/2)^(-2*(1.5))- 
    c1[4]*(1+x/2)^(-2*(2))-c1[5]*(1+x/2)^(-2*(2.5))- 
    c1[6]*(1+x/2)^(-2*(3))-c1[7]*(1+x/2)^(-2*(3.5))- 
    c1[8]*(1+x/2)^(-2*(4))-c1[9]*(1+x/2)^(-2*(4.5))- 
    c1[10]*(1+x/2)^(-2*(5))-c1[11]*(1+x/2)^(-2*(5.5))
  s1<- uniroot(function1, c(0,1))$root
  
  function2 <- function(x) as.numeric(dirty[i, 2])- c2[1]*(1+x/2)^(-2*(0.5)) - 
    c2[2]*(1+x/2)^(-2*(1))-c2[3]*(1+x/2)^(-2*(1.5))- 
    c2[4]*(1+x/2)^(-2*(2))-c2[5]*(1+x/2)^(-2*(2.5))- 
    c2[6]*(1+x/2)^(-2*(3))-c2[7]*(1+x/2)^(-2*(3.5))- 
    c2[8]*(1+x/2)^(-2*(4))-c2[9]*(1+x/2)^(-2*(4.5))- 
    c2[10]*(1+x/2)^(-2*(5))-c2[11]*(1+x/2)^(-2*(5.5))
  s2<- uniroot(function2, c(0,1))$root
  
  function3 <- function(x) as.numeric(dirty[i, 3])-c3[1]*(1+x/2)^(-2*(0.5))- 
    c3[2]*(1+x/2)^(-2*(1))-c3[3]*(1+x/2)^(-2*(1.5))- 
    c3[4]*(1+x/2)^(-2*(2))-c3[5]*(1+x/2)^(-2*(2.5))- 
    c3[6]*(1+x/2)^(-2*(3))-c3[7]*(1+x/2)^(-2*(3.5))- 
    c3[8]*(1+x/2)^(-2*(4))-c3[9]*(1+x/2)^(-2*(4.5))- 
    c3[10]*(1+x/2)^(-2*(5))-c3[11]*(1+x/2)^(-2*(5.5))- 
    c3[12]*(1+x/2)^(-2*(6))-c3[13]*(1+x/2)^(-2*(6.5))
  s3<- uniroot(function3, c(0,1))$root
  
  function4 <- function(x) as.numeric(dirty[i, 4])-c4[1]*(1+x/2)^(-2*(0.5))- 
    c4[2]*(1+x/2)^(-2*(1))-c4[3]*(1+x/2)^(-2*(1.5))- 
    c4[4]*(1+x/2)^(-2*(2))-c4[5]*(1+x/2)^(-2*(2.5))- 
    c4[6]*(1+x/2)^(-2*(3))-c4[7]*(1+x/2)^(-2*(3.5))- 
    c4[8]*(1+x/2)^(-2*(4))-c4[9]*(1+x/2)^(-2*(4.5))-
    c4[10]*(1+x/2)^(-2*(5))-c4[11]*(1+x/2)^(-2*(5.5))- 
    c4[12]*(1+x/2)^(-2*(6))-c4[13]*(1+x/2)^(-2*(6.5))
  s4<- uniroot(function4, c(0,1))$root
  
  function5 <- function(x) as.numeric(dirty[i, 5])-c5[1]*(1+x/2)^(-2*(0.5))- 
    c5[2]*(1+x/2)^(-2*(1))-c5[3]*(1+x/2)^(-2*(1.5))- 
    c5[4]*(1+x/2)^(-2*(2))-c5[5]*(1+x/2)^(-2*(2.5))- 
    c5[6]*(1+x/2)^(-2*(3))-c5[7]*(1+x/2)^(-2*(3.5))- 
    c5[8]*(1+x/2)^(-2*(4))-c5[9]*(1+x/2)^(-2*(4.5))- 
    c5[10]*(1+x/2)^(-2*(5))-c5[11]*(1+x/2)^(-2*(5.5))- 
    c5[12]*(1+x/2)^(-2*(6))-c5[13]*(1+x/2)^(-2*(6.5))- 
    c5[14]*(1+x/2)^(-2*(7))
  s5<- uniroot(function5, c(0,1))$root
  
  function6 <- function(x) as.numeric(dirty[i, 6])-c6[1]*(1+x/2)^(-2*(0.5))- 
    c6[2]*(1+x/2)^(-2*(1))-c6[3]*(1+x/2)^(-2*(1.5))- 
    c6[4]*(1+x/2)^(-2*(2))-c6[5]*(1+x/2)^(-2*(2.5))- 
    c6[6]*(1+x/2)^(-2*(3))-c6[7]*(1+x/2)^(-2*(3.5))- 
    c6[8]*(1+x/2)^(-2*(4))-c6[9]*(1+x/2)^(-2*(4.5))- 
    c6[10]*(1+x/2)^(-2*(5))-c6[11]*(1+x/2)^(-2*(5.5))- 
    c6[12]*(1+x/2)^(-2*(6))-c6[13]*(1+x/2)^(-2*(6.5))-
    c6[14]*(1+x/2)^(-2*(7))-c6[15]*(1+x/2)^(-2*(7.5))- 
    c6[16]*(1+x/2)^(-2*(8))
  s6<- uniroot(function6, c(0,1))$root
  
  function7 <- function(x) as.numeric(dirty[i, 7])-c7[1]*(1+x/2)^(-2*(0.5))- 
    c7[2]*(1+x/2)^(-2*(1))-c7[3]*(1+x/2)^(-2*(1.5))- 
    c7[4]*(1+x/2)^(-2*(2))-c7[5]*(1+x/2)^(-2*(2.5))- 
    c7[6]*(1+x/2)^(-2*(3))-c7[7]*(1+x/2)^(-2*(3.5))- 
    c7[8]*(1+x/2)^(-2*(4))-c7[9]*(1+x/2)^(-2*(4.5))- 
    c7[10]*(1+x/2)^(-2*(5))-c7[11]*(1+x/2)^(-2*(5.5))- 
    c7[12]*(1+x/2)^(-2*(6))-c7[13]*(1+x/2)^(-2*(6.5))- 
    c7[14]*(1+x/2)^(-2*(7))-c7[15]*(1+x/2)^(-2*(7.5))- 
    c7[16]*(1+x/2)^(-2*(8))-c7[17]*(1+x/2)^(-2*(8.5))
  s7<- uniroot(function7, c(0,1))$root
  
  function8 <- function(x) as.numeric(dirty[i, 8])-c8[1]*(1+x/2)^(-2*(0.5))- 
    c8[2]*(1+x/2)^(-2*(1))-c8[3]*(1+x/2)^(-2*(1.5))- 
    c8[4]*(1+x/2)^(-2*(2))-c8[5]*(1+x/2)^(-2*(2.5))- 
    c8[6]*(1+x/2)^(-2*(3))-c8[7]*(1+x/2)^(-2*(3.5))- 
    c8[8]*(1+x/2)^(-2*(4))-c8[9]*(1+x/2)^(-2*(4.5))- 
    c8[10]*(1+x/2)^(-2*(5))-c8[11]*(1+x/2)^(-2*(5.5))- 
    c8[12]*(1+x/2)^(-2*(6))-c8[13]*(1+x/2)^(-2*(6.5))- 
    c8[14]*(1+x/2)^(-2*(7))-c8[15]*(1+x/2)^(-2*(7.5))- 
    c8[16]*(1+x/2)^(-2*(8))-c8[17]*(1+x/2)^(-2*(8.5))- 
    c8[18]*(1+x/2)^(-2*(9))
  s8<- uniroot(function8, c(0,1))$root
  
  function9 <- function(x) as.numeric(dirty[i, 9])-c9[1]*(1+x/2)^(-2*(0.5))- 
    c9[2]*(1+x/2)^(-2*(1))-c9[3]*(1+x/2)^(-2*(1.5))- 
    c9[4]*(1+x/2)^(-2*(2))-c9[5]*(1+x/2)^(-2*(2.5))- 
    c9[6]*(1+x/2)^(-2*(3))-c9[7]*(1+x/2)^(-2*(3.5))- 
    c9[8]*(1+x/2)^(-2*(4))-c9[9]*(1+x/2)^(-2*(4.5))- 
    c9[10]*(1+x/2)^(-2*(5))-c9[11]*(1+x/2)^(-2*(5.5))- 
    c9[12]*(1+x/2)^(-2*(6))-c9[13]*(1+x/2)^(-2*(6.5))- 
    c9[14]*(1+x/2)^(-2*(7))-c9[15]*(1+x/2)^(-2*(7.5))- 
    c9[16]*(1+x/2)^(-2*(8))-c9[17]*(1+x/2)^(-2*(8.5))- 
    c9[18]*(1+x/2)^(-2*(9))-c9[19]*(1+x/2)^(-2*(9.5))
  s9<- uniroot(function9, c(0,1))$root
  
  function10 <- function(x) as.numeric(dirty[i, 10])-c10[1]*(1+x/2)^(-2*(0.5))- 
    c10[2]*(1+x/2)^(-2*(1))-c10[3]*(1+x/2)^(-2*(1.5))- 
    c10[4]*(1+x/2)^(-2*(2))-c10[5]*(1+x/2)^(-2*(2.5))- 
    c10[6]*(1+x/2)^(-2*(3))-c10[7]*(1+x/2)^(-2*(3.5))- 
    c10[8]*(1+x/2)^(-2*(4))-c10[9]*(1+x/2)^(-2*(4.5))- 
    c10[10]*(1+x/2)^(-2*(5))-c10[11]*(1+x/2)^(-2*(5.5))- 
    c10[12]*(1+x/2)^(-2*(6))-c10[13]*(1+x/2)^(-2*(6.5))- 
    c10[14]*(1+x/2)^(-2*(7))-c10[15]*(1+x/2)^(-2*(7.5))- 
    c10[16]*(1+x/2)^(-2*(8))-c10[17]*(1+x/2)^(-2*(8.5))- 
    c10[18]*(1+x/2)^(-2*(9))-c10[19]*(1+x/2)^(-2*(9.5))- 
    c10[20]*(1+x/2)^(-2*(10))
  s10<- uniroot(function10, c(0,1))$root
  
  rates <- rbind(s1,s2,s3,s4,s5,s6,s7,s8,s9,s10)
  spot[i,] <- rates
}
```


```{r}
# Plot of the Spot curves
## the 10 workdays
day <- c(1,2,3,4,5,6,7,8,9,10)
# Add extra space for the plot so legend can be added
par(mar=c(5, 8, 8, 8), xpd=TRUE)
plot(day, spot[1, ], type = "o", main = "Spot Curves for the Selected Bonds", 
     xlab = "10 workdays start from 2023-01-16", ylab = "Spot rate", ylim = c(0.0255, 0.03), col = "black")
lines(day, as.numeric(spot[2, ]), type = "o", col = "red")
lines(day, as.numeric(spot[3, ]), type = "o", col = "darkorange")
lines(day, as.numeric(spot[4, ]), type = "o", col = "yellow")
lines(day, as.numeric(spot[5, ]), type = "o", col = "aquamarine")
lines(day, as.numeric(spot[6, ]), type = "o", col = "blue")
lines(day, as.numeric(spot[7, ]), type = "o", col = "purple")
lines(day, as.numeric(spot[8, ]), type = "o", col = "darkgreen")
lines(day, as.numeric(spot[9, ]), type = "o", col = "pink")
lines(day, as.numeric(spot[10, ]), type = "o", col = "brown")

colors = c("black", "red", "darkorange", "yellow", "aquamarine4", "blue", "purple", "darkgreen", "pink", "brown")
#Legend
legend("topright", pch = c(15,15), inset = c(-0.4, 0), legend = data$`Bond name`, col = colors, cex = 0.5)
```

## Forward Curve

```{r}
# Used the 1st, 3rd, 5th , 7th, and 9th bonds from the selected data.
# Use different years of bonds to calculate forward rates.
# Details explained in assignment.

# curve 1-1
curve1 <- c()
for (i in 1:10){
  curve1[i] = (1+as.numeric(spot[3, i]))^as.numeric(time[i,3])/(1+as.numeric(spot[1, i]))^as.numeric(time[i,1]) - 1
}

# curve 1-2
curve2 <- c()
for (i in 1:10){
  curve2[i] = (1+as.numeric(spot[5, i]))^as.numeric(time[i,5])/(1+as.numeric(spot[1, i]))^as.numeric(time[i,1]) - 1
}

# curve 1-3
curve3 <- c()
for (i in 1:10){
  curve3[i] = (1+as.numeric(spot[7, i]))^as.numeric(time[i,7])/(1+as.numeric(spot[1, i]))^as.numeric(time[i,1]) - 1
}

# curve 1-4
curve4 <- c()
for (i in 1:10){
  curve4[i] = (1+as.numeric(spot[9, i]))^as.numeric(time[i,9])/(1+as.numeric(spot[1, i]))^as.numeric(time[i,1]) - 1
}

# forward matrix
forward <- rbind(curve1, curve2, curve3, curve4)
```

```{r}
# Plot of forward curves

## the 10 workdays
day <- c(1,2,3,4,5,6,7,8,9,10)
# Add extra space for the plot so legend can be added
par(mar=c(5, 8, 8, 8), xpd=TRUE)
plot(day, curve1, type = "o", main = "Forward Curves for the Selected Bonds", 
     xlab = "10 workdays start from 2023-01-16", ylab = "Forward rate", ylim = c(0,0.2), col = "black")
lines(day, curve2, type = "o", col = "red")
lines(day, curve3, type = "o", col = "darkorange")
lines(day, curve4, type = "o", col = "yellow")
colors = c("black", "red", "darkorange", "yellow")
name <- c("1-1", "1-2", "1-3", "1-4")
#Legend
legend("topright", pch = c(15,15), inset = c(-0.4, 0), legend = name, col = colors, cex = 0.5)

```


## Calculation of covariance for the log-return of yields

```{r}
# selected ytm for duration from 1 year to 5 years
y1 <- ytm[,1]
y3 <- ytm[,3]
y5 <- ytm[,5]
y7 <- ytm[,7]
y9 <- ytm[,9]
ytm2 <- rbind(y1,y3,y5,y7,y9)
```

```{r}
# Initialize log return of the ytm
log_ytm2 <- matrix('numeric', nrow = 5, ncol = 9)
for (i in 1:5){
  for (j in 1:9){
    log_ytm2[i,j] = log(as.numeric(ytm2[i,(j+1)]))/as.numeric(ytm2[i,j])
  }
}

# covariance matrix for log returns of yield
cov_ytm2 <- cov(as.numeric(log_ytm2), as.numeric(log_ytm2))
print(cov_ytm2)
```

```{r}
# eigenvalues and eigenvectors of log ytm covariance matrix
print(eigen(cov_ytm2)$values)
print(eigen(cov_ytm2)$vectors)
```


## Calculation of covariance for the forward rates
```{r}
# covariance matrix for forward rates
cov_forward <- cov(forward, forward)
cov_forward
```

```{r}
# eigenvalues and eigenvectors for the forward rates
print(eigen(cov_forward)$values)
print(eigen(cov_forward)$vectors)
```

